// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatMessage.proto

package org.flmelody.wim.message;

/**
 * <pre>
 * 聊天消息
 * </pre>
 *
 * Protobuf type {@code ChatMessage}
 */
public final class ChatMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ChatMessage)
    ChatMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ChatMessage.newBuilder() to construct.
  private ChatMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ChatMessage() {
    conversation_ = "";
    random_ = "";
    from_ = "";
    to_ = "";
    content_ = "";
    client_ = 0;
    type_ = 0;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new ChatMessage();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ChatMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            conversation_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            random_ = s;
            break;
          }
          case 24: {

            seq_ = input.readUInt64();
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            from_ = s;
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            to_ = s;
            break;
          }
          case 50: {
            String s = input.readStringRequireUtf8();

            content_ = s;
            break;
          }
          case 56: {

            withdraw_ = input.readBool();
            break;
          }
          case 66: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (timestamp_ != null) {
              subBuilder = timestamp_.toBuilder();
            }
            timestamp_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(timestamp_);
              timestamp_ = subBuilder.buildPartial();
            }

            break;
          }
          case 72: {
            int rawValue = input.readEnum();

            client_ = rawValue;
            break;
          }
          case 80: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ChatMessageOuterClass.internal_static_ChatMessage_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ChatMessageOuterClass.internal_static_ChatMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ChatMessage.class, Builder.class);
  }

  public static final int CONVERSATION_FIELD_NUMBER = 1;
  private volatile Object conversation_;
  /**
   * <pre>
   * 会话id
   * </pre>
   *
   * <code>string conversation = 1;</code>
   * @return The conversation.
   */
  @Override
  public String getConversation() {
    Object ref = conversation_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      conversation_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 会话id
   * </pre>
   *
   * <code>string conversation = 1;</code>
   * @return The bytes for conversation.
   */
  @Override
  public com.google.protobuf.ByteString
      getConversationBytes() {
    Object ref = conversation_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      conversation_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RANDOM_FIELD_NUMBER = 2;
  private volatile Object random_;
  /**
   * <pre>
   * 该会话内消息唯一随机数
   * </pre>
   *
   * <code>string random = 2;</code>
   * @return The random.
   */
  @Override
  public String getRandom() {
    Object ref = random_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      random_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 该会话内消息唯一随机数
   * </pre>
   *
   * <code>string random = 2;</code>
   * @return The bytes for random.
   */
  @Override
  public com.google.protobuf.ByteString
      getRandomBytes() {
    Object ref = random_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      random_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEQ_FIELD_NUMBER = 3;
  private long seq_;
  /**
   * <pre>
   * 该消息seq,客户端无需设置,回发消息有返回
   * </pre>
   *
   * <code>uint64 seq = 3;</code>
   * @return The seq.
   */
  @Override
  public long getSeq() {
    return seq_;
  }

  public static final int FROM_FIELD_NUMBER = 4;
  private volatile Object from_;
  /**
   * <pre>
   *发送人
   * </pre>
   *
   * <code>string from = 4;</code>
   * @return The from.
   */
  @Override
  public String getFrom() {
    Object ref = from_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      from_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *发送人
   * </pre>
   *
   * <code>string from = 4;</code>
   * @return The bytes for from.
   */
  @Override
  public com.google.protobuf.ByteString
      getFromBytes() {
    Object ref = from_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      from_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TO_FIELD_NUMBER = 5;
  private volatile Object to_;
  /**
   * <pre>
   * 接收人
   * </pre>
   *
   * <code>string to = 5;</code>
   * @return The to.
   */
  @Override
  public String getTo() {
    Object ref = to_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      to_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 接收人
   * </pre>
   *
   * <code>string to = 5;</code>
   * @return The bytes for to.
   */
  @Override
  public com.google.protobuf.ByteString
      getToBytes() {
    Object ref = to_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      to_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTENT_FIELD_NUMBER = 6;
  private volatile Object content_;
  /**
   * <pre>
   * 消息体
   * </pre>
   *
   * <code>string content = 6;</code>
   * @return The content.
   */
  @Override
  public String getContent() {
    Object ref = content_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      content_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 消息体
   * </pre>
   *
   * <code>string content = 6;</code>
   * @return The bytes for content.
   */
  @Override
  public com.google.protobuf.ByteString
      getContentBytes() {
    Object ref = content_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      content_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WITHDRAW_FIELD_NUMBER = 7;
  private boolean withdraw_;
  /**
   * <pre>
   * 消息是否被撤回  当存在同一seq时需比对最新收到的是否为撤回消息
   * </pre>
   *
   * <code>bool withdraw = 7;</code>
   * @return The withdraw.
   */
  @Override
  public boolean getWithdraw() {
    return withdraw_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 8;
  private com.google.protobuf.Timestamp timestamp_;
  /**
   * <pre>
   * 发包时间
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 8;</code>
   * @return Whether the timestamp field is set.
   */
  @Override
  public boolean hasTimestamp() {
    return timestamp_ != null;
  }
  /**
   * <pre>
   * 发包时间
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 8;</code>
   * @return The timestamp.
   */
  @Override
  public com.google.protobuf.Timestamp getTimestamp() {
    return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
  }
  /**
   * <pre>
   * 发包时间
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 8;</code>
   */
  @Override
  public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
    return getTimestamp();
  }

  public static final int CLIENT_FIELD_NUMBER = 9;
  private int client_;
  /**
   * <pre>
   * 客户端类型
   * </pre>
   *
   * <code>.ChatClient client = 9;</code>
   * @return The enum numeric value on the wire for client.
   */
  @Override public int getClientValue() {
    return client_;
  }
  /**
   * <pre>
   * 客户端类型
   * </pre>
   *
   * <code>.ChatClient client = 9;</code>
   * @return The client.
   */
  @Override public ChatClient getClient() {
    @SuppressWarnings("deprecation")
    ChatClient result = ChatClient.valueOf(client_);
    return result == null ? ChatClient.UNRECOGNIZED : result;
  }

  public static final int TYPE_FIELD_NUMBER = 10;
  private int type_;
  /**
   * <pre>
   * 聊天类型
   * </pre>
   *
   * <code>.ChatType type = 10;</code>
   * @return The enum numeric value on the wire for type.
   */
  @Override public int getTypeValue() {
    return type_;
  }
  /**
   * <pre>
   * 聊天类型
   * </pre>
   *
   * <code>.ChatType type = 10;</code>
   * @return The type.
   */
  @Override public ChatType getType() {
    @SuppressWarnings("deprecation")
    ChatType result = ChatType.valueOf(type_);
    return result == null ? ChatType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getConversationBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, conversation_);
    }
    if (!getRandomBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, random_);
    }
    if (seq_ != 0L) {
      output.writeUInt64(3, seq_);
    }
    if (!getFromBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, from_);
    }
    if (!getToBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, to_);
    }
    if (!getContentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, content_);
    }
    if (withdraw_ != false) {
      output.writeBool(7, withdraw_);
    }
    if (timestamp_ != null) {
      output.writeMessage(8, getTimestamp());
    }
    if (client_ != ChatClient.UNKNOWN.getNumber()) {
      output.writeEnum(9, client_);
    }
    if (type_ != ChatType.SINGLE.getNumber()) {
      output.writeEnum(10, type_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getConversationBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, conversation_);
    }
    if (!getRandomBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, random_);
    }
    if (seq_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, seq_);
    }
    if (!getFromBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, from_);
    }
    if (!getToBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, to_);
    }
    if (!getContentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, content_);
    }
    if (withdraw_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, withdraw_);
    }
    if (timestamp_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getTimestamp());
    }
    if (client_ != ChatClient.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(9, client_);
    }
    if (type_ != ChatType.SINGLE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(10, type_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ChatMessage)) {
      return super.equals(obj);
    }
    ChatMessage other = (ChatMessage) obj;

    if (!getConversation()
        .equals(other.getConversation())) return false;
    if (!getRandom()
        .equals(other.getRandom())) return false;
    if (getSeq()
        != other.getSeq()) return false;
    if (!getFrom()
        .equals(other.getFrom())) return false;
    if (!getTo()
        .equals(other.getTo())) return false;
    if (!getContent()
        .equals(other.getContent())) return false;
    if (getWithdraw()
        != other.getWithdraw()) return false;
    if (hasTimestamp() != other.hasTimestamp()) return false;
    if (hasTimestamp()) {
      if (!getTimestamp()
          .equals(other.getTimestamp())) return false;
    }
    if (client_ != other.client_) return false;
    if (type_ != other.type_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONVERSATION_FIELD_NUMBER;
    hash = (53 * hash) + getConversation().hashCode();
    hash = (37 * hash) + RANDOM_FIELD_NUMBER;
    hash = (53 * hash) + getRandom().hashCode();
    hash = (37 * hash) + SEQ_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSeq());
    hash = (37 * hash) + FROM_FIELD_NUMBER;
    hash = (53 * hash) + getFrom().hashCode();
    hash = (37 * hash) + TO_FIELD_NUMBER;
    hash = (53 * hash) + getTo().hashCode();
    hash = (37 * hash) + CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getContent().hashCode();
    hash = (37 * hash) + WITHDRAW_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getWithdraw());
    if (hasTimestamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
    }
    hash = (37 * hash) + CLIENT_FIELD_NUMBER;
    hash = (53 * hash) + client_;
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ChatMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ChatMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ChatMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ChatMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ChatMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ChatMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ChatMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ChatMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ChatMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ChatMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ChatMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ChatMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ChatMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 聊天消息
   * </pre>
   *
   * Protobuf type {@code ChatMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ChatMessage)
      ChatMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ChatMessageOuterClass.internal_static_ChatMessage_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ChatMessageOuterClass.internal_static_ChatMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ChatMessage.class, Builder.class);
    }

    // Construct using org.flmelody.wim.message.ChatMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      conversation_ = "";

      random_ = "";

      seq_ = 0L;

      from_ = "";

      to_ = "";

      content_ = "";

      withdraw_ = false;

      if (timestampBuilder_ == null) {
        timestamp_ = null;
      } else {
        timestamp_ = null;
        timestampBuilder_ = null;
      }
      client_ = 0;

      type_ = 0;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ChatMessageOuterClass.internal_static_ChatMessage_descriptor;
    }

    @Override
    public ChatMessage getDefaultInstanceForType() {
      return ChatMessage.getDefaultInstance();
    }

    @Override
    public ChatMessage build() {
      ChatMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ChatMessage buildPartial() {
      ChatMessage result = new ChatMessage(this);
      result.conversation_ = conversation_;
      result.random_ = random_;
      result.seq_ = seq_;
      result.from_ = from_;
      result.to_ = to_;
      result.content_ = content_;
      result.withdraw_ = withdraw_;
      if (timestampBuilder_ == null) {
        result.timestamp_ = timestamp_;
      } else {
        result.timestamp_ = timestampBuilder_.build();
      }
      result.client_ = client_;
      result.type_ = type_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ChatMessage) {
        return mergeFrom((ChatMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ChatMessage other) {
      if (other == ChatMessage.getDefaultInstance()) return this;
      if (!other.getConversation().isEmpty()) {
        conversation_ = other.conversation_;
        onChanged();
      }
      if (!other.getRandom().isEmpty()) {
        random_ = other.random_;
        onChanged();
      }
      if (other.getSeq() != 0L) {
        setSeq(other.getSeq());
      }
      if (!other.getFrom().isEmpty()) {
        from_ = other.from_;
        onChanged();
      }
      if (!other.getTo().isEmpty()) {
        to_ = other.to_;
        onChanged();
      }
      if (!other.getContent().isEmpty()) {
        content_ = other.content_;
        onChanged();
      }
      if (other.getWithdraw() != false) {
        setWithdraw(other.getWithdraw());
      }
      if (other.hasTimestamp()) {
        mergeTimestamp(other.getTimestamp());
      }
      if (other.client_ != 0) {
        setClientValue(other.getClientValue());
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ChatMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ChatMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object conversation_ = "";
    /**
     * <pre>
     * 会话id
     * </pre>
     *
     * <code>string conversation = 1;</code>
     * @return The conversation.
     */
    public String getConversation() {
      Object ref = conversation_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        conversation_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 会话id
     * </pre>
     *
     * <code>string conversation = 1;</code>
     * @return The bytes for conversation.
     */
    public com.google.protobuf.ByteString
        getConversationBytes() {
      Object ref = conversation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        conversation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 会话id
     * </pre>
     *
     * <code>string conversation = 1;</code>
     * @param value The conversation to set.
     * @return This builder for chaining.
     */
    public Builder setConversation(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      conversation_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 会话id
     * </pre>
     *
     * <code>string conversation = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearConversation() {
      
      conversation_ = getDefaultInstance().getConversation();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 会话id
     * </pre>
     *
     * <code>string conversation = 1;</code>
     * @param value The bytes for conversation to set.
     * @return This builder for chaining.
     */
    public Builder setConversationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      conversation_ = value;
      onChanged();
      return this;
    }

    private Object random_ = "";
    /**
     * <pre>
     * 该会话内消息唯一随机数
     * </pre>
     *
     * <code>string random = 2;</code>
     * @return The random.
     */
    public String getRandom() {
      Object ref = random_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        random_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 该会话内消息唯一随机数
     * </pre>
     *
     * <code>string random = 2;</code>
     * @return The bytes for random.
     */
    public com.google.protobuf.ByteString
        getRandomBytes() {
      Object ref = random_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        random_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 该会话内消息唯一随机数
     * </pre>
     *
     * <code>string random = 2;</code>
     * @param value The random to set.
     * @return This builder for chaining.
     */
    public Builder setRandom(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      random_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 该会话内消息唯一随机数
     * </pre>
     *
     * <code>string random = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRandom() {
      
      random_ = getDefaultInstance().getRandom();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 该会话内消息唯一随机数
     * </pre>
     *
     * <code>string random = 2;</code>
     * @param value The bytes for random to set.
     * @return This builder for chaining.
     */
    public Builder setRandomBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      random_ = value;
      onChanged();
      return this;
    }

    private long seq_ ;
    /**
     * <pre>
     * 该消息seq,客户端无需设置,回发消息有返回
     * </pre>
     *
     * <code>uint64 seq = 3;</code>
     * @return The seq.
     */
    @Override
    public long getSeq() {
      return seq_;
    }
    /**
     * <pre>
     * 该消息seq,客户端无需设置,回发消息有返回
     * </pre>
     *
     * <code>uint64 seq = 3;</code>
     * @param value The seq to set.
     * @return This builder for chaining.
     */
    public Builder setSeq(long value) {
      
      seq_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 该消息seq,客户端无需设置,回发消息有返回
     * </pre>
     *
     * <code>uint64 seq = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeq() {
      
      seq_ = 0L;
      onChanged();
      return this;
    }

    private Object from_ = "";
    /**
     * <pre>
     *发送人
     * </pre>
     *
     * <code>string from = 4;</code>
     * @return The from.
     */
    public String getFrom() {
      Object ref = from_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        from_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *发送人
     * </pre>
     *
     * <code>string from = 4;</code>
     * @return The bytes for from.
     */
    public com.google.protobuf.ByteString
        getFromBytes() {
      Object ref = from_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        from_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *发送人
     * </pre>
     *
     * <code>string from = 4;</code>
     * @param value The from to set.
     * @return This builder for chaining.
     */
    public Builder setFrom(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      from_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *发送人
     * </pre>
     *
     * <code>string from = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFrom() {
      
      from_ = getDefaultInstance().getFrom();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *发送人
     * </pre>
     *
     * <code>string from = 4;</code>
     * @param value The bytes for from to set.
     * @return This builder for chaining.
     */
    public Builder setFromBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      from_ = value;
      onChanged();
      return this;
    }

    private Object to_ = "";
    /**
     * <pre>
     * 接收人
     * </pre>
     *
     * <code>string to = 5;</code>
     * @return The to.
     */
    public String getTo() {
      Object ref = to_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        to_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 接收人
     * </pre>
     *
     * <code>string to = 5;</code>
     * @return The bytes for to.
     */
    public com.google.protobuf.ByteString
        getToBytes() {
      Object ref = to_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 接收人
     * </pre>
     *
     * <code>string to = 5;</code>
     * @param value The to to set.
     * @return This builder for chaining.
     */
    public Builder setTo(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      to_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 接收人
     * </pre>
     *
     * <code>string to = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTo() {
      
      to_ = getDefaultInstance().getTo();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 接收人
     * </pre>
     *
     * <code>string to = 5;</code>
     * @param value The bytes for to to set.
     * @return This builder for chaining.
     */
    public Builder setToBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      to_ = value;
      onChanged();
      return this;
    }

    private Object content_ = "";
    /**
     * <pre>
     * 消息体
     * </pre>
     *
     * <code>string content = 6;</code>
     * @return The content.
     */
    public String getContent() {
      Object ref = content_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 消息体
     * </pre>
     *
     * <code>string content = 6;</code>
     * @return The bytes for content.
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 消息体
     * </pre>
     *
     * <code>string content = 6;</code>
     * @param value The content to set.
     * @return This builder for chaining.
     */
    public Builder setContent(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      content_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息体
     * </pre>
     *
     * <code>string content = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearContent() {
      
      content_ = getDefaultInstance().getContent();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息体
     * </pre>
     *
     * <code>string content = 6;</code>
     * @param value The bytes for content to set.
     * @return This builder for chaining.
     */
    public Builder setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      content_ = value;
      onChanged();
      return this;
    }

    private boolean withdraw_ ;
    /**
     * <pre>
     * 消息是否被撤回  当存在同一seq时需比对最新收到的是否为撤回消息
     * </pre>
     *
     * <code>bool withdraw = 7;</code>
     * @return The withdraw.
     */
    @Override
    public boolean getWithdraw() {
      return withdraw_;
    }
    /**
     * <pre>
     * 消息是否被撤回  当存在同一seq时需比对最新收到的是否为撤回消息
     * </pre>
     *
     * <code>bool withdraw = 7;</code>
     * @param value The withdraw to set.
     * @return This builder for chaining.
     */
    public Builder setWithdraw(boolean value) {
      
      withdraw_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息是否被撤回  当存在同一seq时需比对最新收到的是否为撤回消息
     * </pre>
     *
     * <code>bool withdraw = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearWithdraw() {
      
      withdraw_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp timestamp_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
    /**
     * <pre>
     * 发包时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 8;</code>
     * @return Whether the timestamp field is set.
     */
    public boolean hasTimestamp() {
      return timestampBuilder_ != null || timestamp_ != null;
    }
    /**
     * <pre>
     * 发包时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 8;</code>
     * @return The timestamp.
     */
    public com.google.protobuf.Timestamp getTimestamp() {
      if (timestampBuilder_ == null) {
        return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      } else {
        return timestampBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 发包时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 8;</code>
     */
    public Builder setTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timestamp_ = value;
        onChanged();
      } else {
        timestampBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 发包时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 8;</code>
     */
    public Builder setTimestamp(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timestampBuilder_ == null) {
        timestamp_ = builderForValue.build();
        onChanged();
      } else {
        timestampBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 发包时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 8;</code>
     */
    public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (timestamp_ != null) {
          timestamp_ =
            com.google.protobuf.Timestamp.newBuilder(timestamp_).mergeFrom(value).buildPartial();
        } else {
          timestamp_ = value;
        }
        onChanged();
      } else {
        timestampBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 发包时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 8;</code>
     */
    public Builder clearTimestamp() {
      if (timestampBuilder_ == null) {
        timestamp_ = null;
        onChanged();
      } else {
        timestamp_ = null;
        timestampBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 发包时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 8;</code>
     */
    public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
      
      onChanged();
      return getTimestampFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 发包时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 8;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      if (timestampBuilder_ != null) {
        return timestampBuilder_.getMessageOrBuilder();
      } else {
        return timestamp_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      }
    }
    /**
     * <pre>
     * 发包时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getTimestampFieldBuilder() {
      if (timestampBuilder_ == null) {
        timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getTimestamp(),
                getParentForChildren(),
                isClean());
        timestamp_ = null;
      }
      return timestampBuilder_;
    }

    private int client_ = 0;
    /**
     * <pre>
     * 客户端类型
     * </pre>
     *
     * <code>.ChatClient client = 9;</code>
     * @return The enum numeric value on the wire for client.
     */
    @Override public int getClientValue() {
      return client_;
    }
    /**
     * <pre>
     * 客户端类型
     * </pre>
     *
     * <code>.ChatClient client = 9;</code>
     * @param value The enum numeric value on the wire for client to set.
     * @return This builder for chaining.
     */
    public Builder setClientValue(int value) {
      
      client_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 客户端类型
     * </pre>
     *
     * <code>.ChatClient client = 9;</code>
     * @return The client.
     */
    @Override
    public ChatClient getClient() {
      @SuppressWarnings("deprecation")
      ChatClient result = ChatClient.valueOf(client_);
      return result == null ? ChatClient.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 客户端类型
     * </pre>
     *
     * <code>.ChatClient client = 9;</code>
     * @param value The client to set.
     * @return This builder for chaining.
     */
    public Builder setClient(ChatClient value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      client_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 客户端类型
     * </pre>
     *
     * <code>.ChatClient client = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearClient() {
      
      client_ = 0;
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <pre>
     * 聊天类型
     * </pre>
     *
     * <code>.ChatType type = 10;</code>
     * @return The enum numeric value on the wire for type.
     */
    @Override public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * 聊天类型
     * </pre>
     *
     * <code>.ChatType type = 10;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 聊天类型
     * </pre>
     *
     * <code>.ChatType type = 10;</code>
     * @return The type.
     */
    @Override
    public ChatType getType() {
      @SuppressWarnings("deprecation")
      ChatType result = ChatType.valueOf(type_);
      return result == null ? ChatType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 聊天类型
     * </pre>
     *
     * <code>.ChatType type = 10;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(ChatType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 聊天类型
     * </pre>
     *
     * <code>.ChatType type = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ChatMessage)
  }

  // @@protoc_insertion_point(class_scope:ChatMessage)
  private static final ChatMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ChatMessage();
  }

  public static ChatMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChatMessage>
      PARSER = new com.google.protobuf.AbstractParser<ChatMessage>() {
    @Override
    public ChatMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ChatMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ChatMessage> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ChatMessage> getParserForType() {
    return PARSER;
  }

  @Override
  public ChatMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

