// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatAck.proto

package org.flmelody.wim.message;

/**
 * <pre>
 * 客户端收到消息后回复确认包
 * </pre>
 *
 * Protobuf type {@code ChatAck}
 */
public final class ChatAck extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ChatAck)
    ChatAckOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ChatAck.newBuilder() to construct.
  private ChatAck(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ChatAck() {
    conversation_ = "";
    from_ = "";
    client_ = 0;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new ChatAck();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ChatAck(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            conversation_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            from_ = s;
            break;
          }
          case 24: {

            seq_ = input.readUInt64();
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            client_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ChatAckOuterClass.internal_static_ChatAck_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ChatAckOuterClass.internal_static_ChatAck_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ChatAck.class, Builder.class);
  }

  public static final int CONVERSATION_FIELD_NUMBER = 1;
  private volatile Object conversation_;
  /**
   * <pre>
   * 会话id
   * </pre>
   *
   * <code>string conversation = 1;</code>
   * @return The conversation.
   */
  @Override
  public String getConversation() {
    Object ref = conversation_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      conversation_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 会话id
   * </pre>
   *
   * <code>string conversation = 1;</code>
   * @return The bytes for conversation.
   */
  @Override
  public com.google.protobuf.ByteString
      getConversationBytes() {
    Object ref = conversation_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      conversation_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FROM_FIELD_NUMBER = 2;
  private volatile Object from_;
  /**
   * <pre>
   * 消息发送人
   * </pre>
   *
   * <code>string from = 2;</code>
   * @return The from.
   */
  @Override
  public String getFrom() {
    Object ref = from_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      from_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 消息发送人
   * </pre>
   *
   * <code>string from = 2;</code>
   * @return The bytes for from.
   */
  @Override
  public com.google.protobuf.ByteString
      getFromBytes() {
    Object ref = from_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      from_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEQ_FIELD_NUMBER = 3;
  private long seq_;
  /**
   * <pre>
   * 收到消息的seq
   * </pre>
   *
   * <code>uint64 seq = 3;</code>
   * @return The seq.
   */
  @Override
  public long getSeq() {
    return seq_;
  }

  public static final int CLIENT_FIELD_NUMBER = 4;
  private int client_;
  /**
   * <pre>
   * 客户端类型
   * </pre>
   *
   * <code>.ChatClient client = 4;</code>
   * @return The enum numeric value on the wire for client.
   */
  @Override public int getClientValue() {
    return client_;
  }
  /**
   * <pre>
   * 客户端类型
   * </pre>
   *
   * <code>.ChatClient client = 4;</code>
   * @return The client.
   */
  @Override public ChatClient getClient() {
    @SuppressWarnings("deprecation")
    ChatClient result = ChatClient.valueOf(client_);
    return result == null ? ChatClient.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getConversationBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, conversation_);
    }
    if (!getFromBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, from_);
    }
    if (seq_ != 0L) {
      output.writeUInt64(3, seq_);
    }
    if (client_ != ChatClient.UNKNOWN.getNumber()) {
      output.writeEnum(4, client_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getConversationBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, conversation_);
    }
    if (!getFromBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, from_);
    }
    if (seq_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, seq_);
    }
    if (client_ != ChatClient.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, client_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ChatAck)) {
      return super.equals(obj);
    }
    ChatAck other = (ChatAck) obj;

    if (!getConversation()
        .equals(other.getConversation())) return false;
    if (!getFrom()
        .equals(other.getFrom())) return false;
    if (getSeq()
        != other.getSeq()) return false;
    if (client_ != other.client_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONVERSATION_FIELD_NUMBER;
    hash = (53 * hash) + getConversation().hashCode();
    hash = (37 * hash) + FROM_FIELD_NUMBER;
    hash = (53 * hash) + getFrom().hashCode();
    hash = (37 * hash) + SEQ_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSeq());
    hash = (37 * hash) + CLIENT_FIELD_NUMBER;
    hash = (53 * hash) + client_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ChatAck parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ChatAck parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ChatAck parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ChatAck parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ChatAck parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ChatAck parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ChatAck parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ChatAck parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ChatAck parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ChatAck parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ChatAck parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ChatAck parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ChatAck prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 客户端收到消息后回复确认包
   * </pre>
   *
   * Protobuf type {@code ChatAck}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ChatAck)
      ChatAckOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ChatAckOuterClass.internal_static_ChatAck_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ChatAckOuterClass.internal_static_ChatAck_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ChatAck.class, Builder.class);
    }

    // Construct using org.flmelody.wim.message.ChatAck.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      conversation_ = "";

      from_ = "";

      seq_ = 0L;

      client_ = 0;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ChatAckOuterClass.internal_static_ChatAck_descriptor;
    }

    @Override
    public ChatAck getDefaultInstanceForType() {
      return ChatAck.getDefaultInstance();
    }

    @Override
    public ChatAck build() {
      ChatAck result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ChatAck buildPartial() {
      ChatAck result = new ChatAck(this);
      result.conversation_ = conversation_;
      result.from_ = from_;
      result.seq_ = seq_;
      result.client_ = client_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ChatAck) {
        return mergeFrom((ChatAck)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ChatAck other) {
      if (other == ChatAck.getDefaultInstance()) return this;
      if (!other.getConversation().isEmpty()) {
        conversation_ = other.conversation_;
        onChanged();
      }
      if (!other.getFrom().isEmpty()) {
        from_ = other.from_;
        onChanged();
      }
      if (other.getSeq() != 0L) {
        setSeq(other.getSeq());
      }
      if (other.client_ != 0) {
        setClientValue(other.getClientValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ChatAck parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ChatAck) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object conversation_ = "";
    /**
     * <pre>
     * 会话id
     * </pre>
     *
     * <code>string conversation = 1;</code>
     * @return The conversation.
     */
    public String getConversation() {
      Object ref = conversation_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        conversation_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 会话id
     * </pre>
     *
     * <code>string conversation = 1;</code>
     * @return The bytes for conversation.
     */
    public com.google.protobuf.ByteString
        getConversationBytes() {
      Object ref = conversation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        conversation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 会话id
     * </pre>
     *
     * <code>string conversation = 1;</code>
     * @param value The conversation to set.
     * @return This builder for chaining.
     */
    public Builder setConversation(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      conversation_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 会话id
     * </pre>
     *
     * <code>string conversation = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearConversation() {
      
      conversation_ = getDefaultInstance().getConversation();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 会话id
     * </pre>
     *
     * <code>string conversation = 1;</code>
     * @param value The bytes for conversation to set.
     * @return This builder for chaining.
     */
    public Builder setConversationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      conversation_ = value;
      onChanged();
      return this;
    }

    private Object from_ = "";
    /**
     * <pre>
     * 消息发送人
     * </pre>
     *
     * <code>string from = 2;</code>
     * @return The from.
     */
    public String getFrom() {
      Object ref = from_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        from_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 消息发送人
     * </pre>
     *
     * <code>string from = 2;</code>
     * @return The bytes for from.
     */
    public com.google.protobuf.ByteString
        getFromBytes() {
      Object ref = from_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        from_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 消息发送人
     * </pre>
     *
     * <code>string from = 2;</code>
     * @param value The from to set.
     * @return This builder for chaining.
     */
    public Builder setFrom(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      from_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息发送人
     * </pre>
     *
     * <code>string from = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFrom() {
      
      from_ = getDefaultInstance().getFrom();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息发送人
     * </pre>
     *
     * <code>string from = 2;</code>
     * @param value The bytes for from to set.
     * @return This builder for chaining.
     */
    public Builder setFromBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      from_ = value;
      onChanged();
      return this;
    }

    private long seq_ ;
    /**
     * <pre>
     * 收到消息的seq
     * </pre>
     *
     * <code>uint64 seq = 3;</code>
     * @return The seq.
     */
    @Override
    public long getSeq() {
      return seq_;
    }
    /**
     * <pre>
     * 收到消息的seq
     * </pre>
     *
     * <code>uint64 seq = 3;</code>
     * @param value The seq to set.
     * @return This builder for chaining.
     */
    public Builder setSeq(long value) {
      
      seq_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 收到消息的seq
     * </pre>
     *
     * <code>uint64 seq = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeq() {
      
      seq_ = 0L;
      onChanged();
      return this;
    }

    private int client_ = 0;
    /**
     * <pre>
     * 客户端类型
     * </pre>
     *
     * <code>.ChatClient client = 4;</code>
     * @return The enum numeric value on the wire for client.
     */
    @Override public int getClientValue() {
      return client_;
    }
    /**
     * <pre>
     * 客户端类型
     * </pre>
     *
     * <code>.ChatClient client = 4;</code>
     * @param value The enum numeric value on the wire for client to set.
     * @return This builder for chaining.
     */
    public Builder setClientValue(int value) {
      
      client_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 客户端类型
     * </pre>
     *
     * <code>.ChatClient client = 4;</code>
     * @return The client.
     */
    @Override
    public ChatClient getClient() {
      @SuppressWarnings("deprecation")
      ChatClient result = ChatClient.valueOf(client_);
      return result == null ? ChatClient.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 客户端类型
     * </pre>
     *
     * <code>.ChatClient client = 4;</code>
     * @param value The client to set.
     * @return This builder for chaining.
     */
    public Builder setClient(ChatClient value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      client_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 客户端类型
     * </pre>
     *
     * <code>.ChatClient client = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearClient() {
      
      client_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ChatAck)
  }

  // @@protoc_insertion_point(class_scope:ChatAck)
  private static final ChatAck DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ChatAck();
  }

  public static ChatAck getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChatAck>
      PARSER = new com.google.protobuf.AbstractParser<ChatAck>() {
    @Override
    public ChatAck parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ChatAck(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ChatAck> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ChatAck> getParserForType() {
    return PARSER;
  }

  @Override
  public ChatAck getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

